name: Deploy

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  NODE_VERSION: 20.0

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Build application
        run: yarn build
        env:
          ENVIRONMENT: ${{ vars.ENVIRONMENT }}
          STORYBLOK_API_TOKEN: ${{ secrets.STORYBLOK_API_TOKEN }}
          BASE_PATH: ${{ vars.BASE_PATH }}
          SITE_URL: ${{ vars.SITE_URL }}
          GTM_ID: ${{ secrets.GTM_ID }}

      - name: Build sitemap
        if: ${{ vars.ENVIRONMENT }} == 'production'
        run: yarn build:sitemap
        env:
          SITE_URL: ${{ vars.SITE_URL }}

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload build
        uses: actions/upload-pages-artifact@v3
        with:
          path: './out'

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
